// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzJfLxhaUE_ChNKUJIbrYfYCmKQ8ttTQ',
    appId: '1:298336761011:web:904081d038a44ae8c62cc6',
    messagingSenderId: '298336761011',
    projectId: 'howdiplomaapp',
    authDomain: 'howdiplomaapp.firebaseapp.com',
    storageBucket: 'howdiplomaapp.firebasestorage.app',
    measurementId: 'G-P3BZYJ8QR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeBBjbShlxaiUSNwI4B5leENcKQpR_o0',
    appId: '1:298336761011:android:3ffa150326998f31c62cc6',
    messagingSenderId: '298336761011',
    projectId: 'howdiplomaapp',
    storageBucket: 'howdiplomaapp.firebasestorage.app',
  );
}
